# Generated by Django 4.1.1 on 2022-10-24 20:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('head_msg', models.CharField(default='Vincent', max_length=200)),
                ('head_body', wagtail.fields.RichTextField(default='Hello world')),
                ('head_btn_link', wagtail.fields.RichTextField(default='Free Consultation')),
                ('info', wagtail.fields.RichTextField(default='Hello world')),
                ('link', wagtail.fields.RichTextField(default='Hello world')),
                ('team', wagtail.fields.StreamField([('teammate', wagtail.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.blocks.CharBlock(form_classname='title')), ('details', wagtail.blocks.CharBlock(form_classname='title'))]))], blank=True, use_json_field=True)),
                ('contact_phone', models.CharField(default='256774559687', max_length=200)),
                ('contact_email', models.EmailField(default='ojaravincent5@gmail.com', max_length=254)),
                ('contact_location', models.CharField(default='Kampala, Uganda', max_length=255)),
                ('b_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('description', wagtail.fields.RichTextField(default='Hello world')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_services', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('price_type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('basis', models.CharField(max_length=200)),
                ('breakdown', wagtail.fields.RichTextField()),
                ('order_link', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_prices', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
