# Generated by Django 4.1.1 on 2023-03-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='head_body',
        ),
    ]
