# Generated by Django 4.1.1 on 2022-09-20 07:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0076_modellogentry_revision'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='b_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(default='ojaravincent5@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_location',
            field=models.CharField(default='Kampala, Uganda', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.IntegerField(default=256774559687),
        ),
        migrations.AddField(
            model_name='homepage',
            name='head_body',
            field=wagtail.fields.RichTextField(default='Hello world'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='head_btn_link',
            field=models.CharField(default='Free Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='head_msg',
            field=models.CharField(default='Vincent', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_content',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.blocks.CharBlock(form_classname='title')), ('description', wagtail.blocks.RichTextBlock())], default='content', use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pricing',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.CharBlock(form_classname='title')), ('price_type', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.CharBlock()), ('basis', wagtail.blocks.CharBlock()), ('breakdown', wagtail.blocks.RichTextBlock()), ('order_link', wagtail.blocks.CharBlock())], default='price', use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team',
            field=wagtail.fields.StreamField([('head', wagtail.blocks.CharBlock(form_classname='title')), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('details', wagtail.blocks.RichTextBlock())], default='team', use_json_field=True),
        ),
    ]
