# Generated by Django 4.1.1 on 2022-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_b_image_homepage_blog_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(default='256774559687', max_length=200),
        ),
    ]
