# Generated by Django 4.1.1 on 2022-09-22 12:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0004_alter_homepage_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team',
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(default='Hello world'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='details',
            field=wagtail.fields.RichTextField(default='Hello world'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info',
            field=wagtail.fields.RichTextField(default='Hello world'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link',
            field=models.CharField(default='Hello world', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='Hello world', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='HomePagePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=200)),
                ('price_type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('basis', models.CharField(max_length=200)),
                ('breakdown', wagtail.fields.RichTextField()),
                ('order_link', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_prices', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
