# Generated by Django 4.1.1 on 2022-09-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_home_content_remove_homepage_pricing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageprices',
            name='heading',
        ),
    ]
