# Generated by Django 4.1.1 on 2022-09-26 16:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_description_homepage_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team',
            field=wagtail.fields.StreamField([('teammate', wagtail.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.blocks.CharBlock(form_classname='title')), ('details', wagtail.blocks.CharBlock(form_classname='title'))]))], blank=True, use_json_field=True),
        ),
    ]
