# Generated by Django 4.1.1 on 2022-09-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blog_feature',
        ),
    ]
