# Generated by Django 4.1.1 on 2023-01-18 09:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(max_length=255)),
                ('story', wagtail.fields.RichTextField()),
                ('testimonials', wagtail.fields.StreamField([('testifier', wagtail.blocks.StructBlock([('testimony', wagtail.blocks.RichTextBlock()), ('profilepic', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.blocks.CharBlock(form_classname='title')), ('profession', wagtail.blocks.CharBlock(form_classname='title'))]))], blank=True, use_json_field=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Us Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
