# Generated by Django 4.1.1 on 2022-09-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Us Page'},
        ),
    ]
